package:
  name: "loprop"
  version: "0.2.2"

source:
  git_url: https://github.com/vahtras/loprop.git


requirements:
  build:
    - python
    - daltools
    - pytest
	

  run:
    - python
    - daltools

test:
  requires:
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/vahtras/loprop
